- name: Firewall Rules
  copy: src=iptables
        dest=/etc/sysconfig/iptables
        owner=root group=root mode=0644
  notify:
    - restart iptables
- name: Firewall Rules
  copy: src=ip6tables
        dest=/etc/sysconfig/ip6tables
        owner=root group=root mode=0644
  notify:
    - restart ip6tables
